"""Add assignment_complete flag to Debate

Revision ID: 1f032f588938
Revises: b47584362314
Create Date: 2025-05-25 18:00:38.629254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f032f588938'
down_revision = 'b47584362314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.drop_column('assignment_complete')

    # ### end Alembic commands ###
