"""finalization split into rooms

Revision ID: 6ce6ccf1ea1e
Revises: ee09ebaf6cf6
Create Date: 2025-11-09 20:58:52.631562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce6ccf1ea1e'
down_revision = 'ee09ebaf6cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalized_rooms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.drop_column('finalized_rooms')

    # ### end Alembic commands ###
