"""migrate free speakers

Revision ID: bd289c0aa07f
Revises: ce386eac0a1a
Create Date: 2025-10-25 14:57:05.385972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd289c0aa07f'
down_revision = 'ce386eac0a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.alter_column('style',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('OPD', 'BP', 'Dynamic', name='debate_style'),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefer_free', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefer_free')

    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.alter_column('style',
               existing_type=sa.Enum('OPD', 'BP', 'Dynamic', name='debate_style'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
