"""add prefer_judging

Revision ID: ce386eac0a1a
Revises: d2b53c8ed2c8
Create Date: 2025-08-02 20:04:26.795563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce386eac0a1a'
down_revision = 'd2b53c8ed2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefer_judging', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefer_judging')
    # ### end Alembic commands ###
