"""some descriptive message here

Revision ID: ee09ebaf6cf6
Revises: bd289c0aa07f
Create Date: 2025-11-09 14:54:02.348267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee09ebaf6cf6'
down_revision = 'bd289c0aa07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.drop_column('rooms')

    # ### end Alembic commands ###
